### ISSUE TITLE
Just a license, readme and gitfile...

### ISSUE THREAD

**Issue by tjoen** [1-MillionParanoidTterabytes/Blender-CarMaker-Addon#1]
So you added a very descriptive license for just a readme and git file?
I must be missing your point...

**Comment by DarthMoulByte** [comment]
It was fun to play with the **ambiguity and double standards of licenses**, if you think about it ... **what is a license?** a case is not a game of double moral and protect something that **if you really want to protect would not show**, and if you will show the public **how to contradict the meaning of the word public** with a stupid license? _Double morality and ambiguity is all I see in people when they ask for their shitty credits and be mentioned in the software or then their license is not worth it!
![terrainhex](https://user-images.githubusercontent.com/24207840/41514232-f311c21c-726a-11e8-80b3-194d9d5ed0b8.png)
_

**Comment by DarthMoulByte** [comment]
@tjoen read this is very very confused and restrictive [Crock](https://github.com/gilbo/cork)

![2018-06-18_20-33-47](https://user-images.githubusercontent.com/24207840/41572002-6fa9583c-733b-11e8-9b29-0e5108e4a395.png)
